grep -c Borderline Run_Indirect1_loc.dat > Indirect_borderline_loc.out
grep -c Borderline Run_Indirect2_loc.dat >> Indirect_borderline_loc.out
grep -c Borderline Run_Indirect3_loc.dat >> Indirect_borderline_loc.out
grep -c Borderline Run_Indirect4_loc.dat >> Indirect_borderline_loc.out
grep -c Borderline Run_Indirect5_loc.dat >> Indirect_borderline_loc.out
grep -c Borderline Run_Indirect6_loc.dat >> Indirect_borderline_loc.out
grep -c Borderline Run_Indirect7_loc.dat >> Indirect_borderline_loc.out
grep -c Borderline Run_Indirect8_loc.dat >> Indirect_borderline_loc.out
grep -c Unlikely Run_Indirect1_loc.dat > Indirect_unlikely_loc.out
grep -c Unlikely Run_Indirect2_loc.dat >> Indirect_unlikely_loc.out
grep -c Unlikely Run_Indirect3_loc.dat >> Indirect_unlikely_loc.out
grep -c Unlikely Run_Indirect4_loc.dat >> Indirect_unlikely_loc.out
grep -c Unlikely Run_Indirect5_loc.dat >> Indirect_unlikely_loc.out
grep -c Unlikely Run_Indirect6_loc.dat >> Indirect_unlikely_loc.out
grep -c Unlikely Run_Indirect7_loc.dat >> Indirect_unlikely_loc.out
grep -c Unlikely Run_Indirect8_loc.dat >> Indirect_unlikely_loc.out
grep -c Consistent Run_Direct_loc.dat > Direct_loc.out
grep -c Borderline Run_Direct_loc.dat >> Direct_loc.out
grep -c Unlikely Run_Direct_loc.dat >> Direct_loc.out

